### ISSUE TITLE
Websockets break after ~ 24 hours

### ISSUE THREAD

**Issue by far-blue** [iverberk/nomad-ui#85] opened 2016-09-06 15:06 UTC
If I leave nomad-ui open overnight I find by the next day all the data has disappeared - no circular diagrams, no members, no nodes etc. This appears to be a websocket thing. If I reload the page, open it in a different browser etc. I see the same problem - no data and no 'frames' back from the websocket.

I can't see any output of use in the nomad logs.

The only solution seems to be to restart the container.

This is using the last 'latest' snapshot.

One point of note is that I'm using Fabio as a proxy - but as the html, css and js content is served correctly and opening in a second browser doesn't fix things I don't think Fabio is the cause of the issue.

**Comment by johnoc2000** [comment] 2016-09-06 15:14
@far blue - I have seen the same behaviour over the last couple of days. Sometimes it is more frequent than 24 hours.
I see it with initial version and snapshot both

**Comment by johnoc2000** [comment] 2016-09-06 15:14
@far-blue - I have seen the same behaviour over the last couple of days. Sometimes it is more frequent than 24 hours.
I see it with initial version and snapshot both

**Comment by iverberk** [comment] 2016-09-06 15:39
Ok, I'll leave it running overnight and see if I can reproduce the problem. One option is that nomad-ui is not getting any new information from Nomad anymore. It uses blocking queries for the most part to get new updates when they happen. Maybe somehow this gets stuck. The other option is that is breaking and/or not accepting (websocket) connections. I'll report back asap, if any more information is available to reproduce this faster or otherwise helpful, please let me know.

**Comment by themalkolm** [comment] 2016-09-06 16:48
Actually WebSocket never reconnects on UI side. These tasks should be canceled when socket is closed:

https://github.com/iverberk/nomad-ui/blob/master/src/sagas/event.js#L83

**Comment by iverberk** [comment] 2016-09-07 06:10
I've been able to reproduce the problem. I'll investigate further. It indeed looks like a server side problem. Will keep you updated.

**Comment by jippi** [comment] 2016-09-07 06:40
if its cross-network, it could simply be a firewall killing long-time connections as part of it's configuration. Most consumer grade routers do not allow multi-day connections to stay alive, idle or not :)

**Comment by iverberk** [comment] 2016-09-07 06:43
yeah I'm not too worried about the websocket connection being terminated, a simple browser reload would fix that or we could build in a reconnection/keep-alive mechanism to make it more resilient. The problem is that opening the webapp in a new window or browser does not yield any information when there definitely should be information from Nomad. Somehow the state is lost in the server and I need to find out why.

**Comment by iverberk** [comment] 2016-09-08 17:05
So I think I know what's causing this and it should be fixed by 78dbff25b8ab52ffb102e7a519cc7050080e3a81

If the websocket connection terminates unexpectedly it would exit the write loop immediately. This means that nothing is checking the send channel anymore. However, there might still be updates being sent to the channel. This caused a blocking send that would never recover. Instead of exiting the write loop I'm just logging any errors and eventually the write loop will be closed automatically when there are no more updates being sent. Please let me know if this fixes the problem.

This does not fix the fact that the browser lost the websocket connection. You will need to reload the page. I'll fix the reconnection in a separate update.

**Comment by iverberk** [comment] 2016-09-12 17:24
Going to close this. Let me know if the problem is not fixed.

**Closed by iverberk** 2016-09-12 17:24 UTC
